<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>slog - simple blog</title>
    <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headMeta() ?>
</head>
<body>

<div class="container">
    <?php echo $this->layout()->content ?>

    <hr />
    <p class="pull-left muted">Powered by the <a href="https://github.com/orbisnull/slog"><b>slog</b></a> - Simple Blog</p>
</div>

</body>
</html>
