<table class="table">
    <tbody>
    <?php foreach ($this->entries as $entry): ?>
    <tr>
        <td><h1><?php echo $this->escape($entry->title) ?></h1></td>
    </tr>
    <tr>
        <td><?php echo ($entry->body) ?></td>
    </tr>
    <tr>
        <td align="right">
            <?php echo ($entry->created) ?>&nbsp;
            <a href="<?php echo $this->url(array("action"=>"edit", "controller"=>"entry")) ?>/id/<?php echo $entry->id ?>"><i class="icon-edit"></i>Редактировать</a>
        </td>
    </tr>

        <?php endforeach ?>
    </tbody>
</table>