<p><a href="<?php echo $this->url(array("action"=>"add", "controller"=>"entry")) ?>"><i class="icon-plus"></i>Добавить запись</a></p>
<table class="table">
    <tbody>
    <?php foreach ($this->entries as $entry): ?>
    <tr>
        <td><h1><a href="<?php echo $this->url(array("action"=>"show", "controller"=>"entry")) ?>/id/<?php echo $entry->id ?>"><?php echo $this->escape($entry->title) ?></a></h1></td>
    </tr>
    <tr>
        <td><?php echo ($entry->body) ?></td>
    </tr>
    <tr>
        <td align="right">
            <?php echo ($entry->created) ?>
            &nbsp;
            <a href="<?php echo $this->url(array("action"=>"edit", "controller"=>"entry")) ?>/id/<?php echo $entry->id ?>"><i class="icon-edit"></i>Редактировать</a>
            &nbsp;
            <a href="<?php echo $this->url(array("action"=>"delete", "controller"=>"entry")) ?>/id/<?php echo $entry->id ?>"><i class="icon-trash"></i>Удалить</a>
        </td>
    </tr>
        <?php endforeach ?>
    </tbody>
</table>